# SD212: Graph mining

# Sparse matrices

The objective of this lab is to learn to work with sparse matrices.

In [2]:
import numpy as np
from scipy import sparse

## CSR format

We first focus on the [CSR](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)  (Compressed Sparse Row) format. Note that there is the [CSC](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format, which is nothing but the CSR format of the transpose matrix.

In [3]:
# random matrix (dense format)
X_dense = np.random.randint(3, size = (10,5))

In [4]:
X_dense

array([[1, 0, 0, 2, 2],
       [2, 0, 0, 1, 1],
       [1, 0, 2, 1, 2],
       [1, 1, 0, 0, 0],
       [2, 1, 2, 2, 1],
       [1, 1, 1, 0, 0],
       [2, 1, 0, 0, 1],
       [1, 1, 0, 2, 2],
       [0, 0, 2, 1, 1],
       [1, 1, 2, 0, 1]])

In [5]:
X_csr = sparse.csr_matrix(X_dense)

In [6]:
X_csr.shape

(10, 5)

In [7]:
X_csr.nnz

34

In [8]:
X_csr

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 34 stored elements in Compressed Sparse Row format>

The data structure consists of 3 vectors:

In [9]:
X_csr.indices

array([0, 3, 4, 0, 3, 4, 0, 2, 3, 4, 0, 1, 0, 1, 2, 3, 4, 0, 1, 2, 0, 1,
       4, 0, 1, 3, 4, 2, 3, 4, 0, 1, 2, 4], dtype=int32)

In [10]:
X_csr.indptr

array([ 0,  3,  6, 10, 12, 17, 20, 23, 27, 30, 34], dtype=int32)

In [11]:
X_csr.data

array([1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1], dtype=int32)

## To do

Can you find the number of non-zeros ``nnz`` and the shape of the matrix from these vectors?

The data part has 34 rows: there 34 non zeros values! There is 10 rows but we cannot find for sure the number of columns, we only know it is >= 5 .

## Arithmetic

Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.

In [12]:
n_row, n_col = 10, 4
X_dense = np.random.randint(2, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [13]:
X_dense

array([[0, 1, 0, 1],
       [0, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 1]])

In [28]:
X

<10x4 sparse matrix of type '<class 'numpy.intc'>'
	with 23 stored elements in Compressed Sparse Row format>

In [14]:
a = np.ones(n_col, dtype=int)

In [15]:
a

array([1, 1, 1, 1])

In [16]:
b = X.dot(a)

In [17]:
b

array([2, 2, 2, 1, 4, 2, 3, 2, 2, 3], dtype=int32)

In [18]:
a = np.ones(n_row, dtype=int)
b = X.T.dot(a)

In [19]:
b

array([7, 4, 8, 4], dtype=int32)

In [20]:
A = np.random.randint(2, size=(n_col, 2))
B = X.dot(A)

In [21]:
A

array([[0, 0],
       [1, 1],
       [0, 1],
       [0, 0]])

In [22]:
B

array([[1, 1],
       [1, 2],
       [0, 1],
       [0, 0],
       [1, 2],
       [1, 2],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]], dtype=int32)

In [23]:
A = sparse.csr_matrix(A)
B = X.dot(A)

In [25]:
A

<4x2 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>

In [24]:
B

<10x2 sparse matrix of type '<class 'numpy.intc'>'
	with 13 stored elements in Compressed Sparse Row format>

In [26]:
B.toarray()

array([[1, 1],
       [1, 2],
       [0, 1],
       [0, 0],
       [1, 2],
       [1, 2],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]], dtype=int32)

In [27]:
X.T.dot(X)

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 16 stored elements in Compressed Sparse Column format>

In [29]:
X.dot(X.T)

<10x10 sparse matrix of type '<class 'numpy.intc'>'
	with 88 stored elements in Compressed Sparse Row format>

In [30]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [31]:
X

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 32 stored elements in Compressed Sparse Row format>

In [32]:
Y = X > 1

In [33]:
Y

<10x5 sparse matrix of type '<class 'numpy.bool_'>'
	with 13 stored elements in Compressed Sparse Row format>

In [34]:
Y.dot(np.ones(n_col, dtype=int))

array([0, 2, 2, 1, 0, 2, 2, 1, 2, 1], dtype=int32)

In [35]:
Y.dot(np.ones(n_col, dtype=bool))

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [36]:
Z = 2 * X + 5 * Y

In [37]:
Z

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 32 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [ ]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Compute the vector of the Euclidean norm of each row.

## Slicing

Sparse matrices can be sliced like numpy arrays.

In [ ]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))

In [ ]:
X = sparse.csr_matrix(X_dense)

In [ ]:
indices = [2, 5, 6]

In [ ]:
X[indices]

In [ ]:
X[:, [1, 3]]

## To do 

Consider the following matrix:

In [ ]:
n_row, n_col = 20, 10
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Select the 5 rows of largest sums and build the corresponding CSR matrix (size 5 x 10).

## DIAG format

In [ ]:
D = sparse.diags(np.arange(10))

In [ ]:
D

In [ ]:
D.data

In [ ]:
D.nnz

In [ ]:
D = sparse.csr_matrix(D)

In [ ]:
D.data

In [ ]:
D.nnz

In [ ]:
n_row, n_col = 10, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

In [ ]:
D.dot(X)

In [ ]:
D = sparse.diags(np.ones(4))

In [ ]:
X.dot(D)

## To do

Consider the following matrix:

In [ ]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

Using sparse diagonal matrices:
* Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero). 

## COO format

Another way to represent sparse matrices is the COO (COOrdinate) format. It is useful to load a matrix from a list of entries.

In [ ]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 3]

In [ ]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [ ]:
X_coo

In [ ]:
X_coo.row

In [ ]:
X_coo.col

In [ ]:
X_coo.data

You can change the format:

In [ ]:
X_csr = X_coo.tocsr()

In [ ]:
X_csr

In [ ]:
X_csr.indices

In [ ]:
X_csr.indptr

In [ ]:
X_csr.data

In [ ]:
X_csr.tocoo()

You can directly load a CSR matrix from COO format:

In [ ]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [ ]:
X_csr

Duplicate entries are summed in CSR, not in COO:

In [ ]:
row = [1, 4, 2, 1]
col = [2, 0, 2, 2]
data = [1, 2, 3, 4]

In [ ]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [ ]:
X_coo

In [ ]:
X_coo.data

In [ ]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [ ]:
X_csr

In [ ]:
X_csr.data

## To do

* Build the following matrix in sparse CSR format:
$$
\begin{pmatrix}
0 & 0 & 1& 2\\
3 & 0& 0& 0\\
0& 0& 4& 0
\end{pmatrix}
$$